import dimensions from '@/lib/image-dimensions.json';

const DIMS: Record<string, number[]> = dimensions;

type Props = Omit<React.ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt'> & {
  src: string;
  alt: string;
  /** false where the surrounding CSS sizes the image without height: auto */
  intrinsicSize?: boolean;
};

/**
 * <img> with a WebP source (generated by scripts/optimise-images.py) and
 * intrinsic width/height from the manifest so the browser reserves space
 * before the image loads. The <picture> wrapper is display: contents, so
 * styling on the img via className behaves as before.
 */
export function Picture({ src, alt, loading = 'lazy', decoding = 'async', intrinsicSize = true, ...rest }: Props) {
  const known = DIMS[src];
  const size = intrinsicSize ? known : undefined;
  const webp = /\.(jpe?g|png)$/i.test(src) && known ? src.replace(/\.(jpe?g|png)$/i, '.webp') : null;
  const img = (
    <img
      src={src}
      alt={alt}
      width={size?.[0]}
      height={size?.[1]}
      loading={loading}
      decoding={decoding}
      {...rest}
    />
  );
  if (!webp) return img;
  return (
    <picture style={{ display: 'contents' }}>
      <source srcSet={webp} type="image/webp" />
      {img}
    </picture>
  );
}
